const $=s=>document.querySelector(s);
const STORAGE_KEY='pathly-product-v1';
const emptyState={screen:'onboarding',onboardingMode:'first',step:0,messages:[],profile:{name:'',goal:'',days:null,minutes:null,foundation:'',style:'',confidence:''},userId:null,plans:[],planRecord:null,plan:null,planNodes:[],planTick:0,planError:null,planClarification:null,confirmedMappings:{},view:'map',deletePathCandidate:null,deletePathError:null};
let storedState={};try{storedState=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch(error){localStorage.removeItem(STORAGE_KEY)}
let state={...emptyState,...storedState,profile:{...emptyState.profile,...(storedState.profile||{})}};
state.plans=Array.isArray(state.plans)?state.plans:[];
const persist=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
function saveRender(){persist();render()}
function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),2200)}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const payload=await response.json();if(!response.ok||!payload.ok){const error=new Error(payload?.error?.message||`请求失败 (${response.status})`);error.code=payload?.error?.code;error.details=payload?.error?.details;throw error}return payload}
const questions=[
 {key:'name',text:'你好，我是 Pathly。开始前，我应该怎么称呼你？',placeholder:'输入你的姓名或昵称',quick:[]},
 {key:'goal',text:'你真正想学会什么？可以描述一个具体结果，而不只是课程名称。',placeholder:'例如：我想能独立解释并实现一个 Transformer',quick:[]},
 {key:'days',text:'你希望用多少天完成这个目标？',placeholder:'输入天数',quick:['7 天','14 天','30 天']},
 {key:'minutes',text:'你每天实际能够投入多少分钟？',placeholder:'输入每天可用分钟数',quick:['30 分钟','60 分钟','90 分钟']},
 {key:'foundation',text:'你已经具备哪些相关基础？',placeholder:'描述已掌握的知识、编程或数学基础',quick:['完全从零开始','有编程基础','有数学基础']},
 {key:'style',text:'你更容易通过什么方式理解新内容？',placeholder:'描述你喜欢的讲解和练习方式',quick:['直觉解释','数学推导','项目实践']},
 {key:'confidence',text:'你对完成这个目标目前有多大信心？',placeholder:'描述你的信心或主要顾虑',quick:['较低','中等','较高']},
 {key:'confirm',text:'请确认右侧画像。确认后，Pathly 会保存画像并根据真实知识图谱生成学习路径。',placeholder:'如需修改，可直接编辑右侧字段',quick:['确认并生成学习路径']}
];
const repeatQuestions=[questions[1],questions[2],questions[3],questions[7]];
function activeQuestions(){return state.onboardingMode==='repeat'?repeatQuestions:questions}
function progress(){const qs=activeQuestions();return Math.round((Math.min(state.step,qs.length-1)/(qs.length-1))*100)}
function onboarding(){
 const qs=activeQuestions(),repeat=state.onboardingMode==='repeat';
 if(!Number.isInteger(state.step)||state.step<0||state.step>=qs.length){state.step=0;state.messages=[];persist()}
 const q=qs[state.step];
 const history=state.messages.map(m=>m.role==='agent'?`<div class="agent-row"><span class="agent-mark">✦</span><div class="bubble">${m.text}</div></div>`:`<div class="bubble user">${m.text}</div>`).join('');
 if(!state.messages.length)setTimeout(()=>{state.messages=[{role:'agent',text:qs[0].text}];persist();render()},0);
 const reuse=repeat?`<div class="reuse-note"><b>已沿用你的个人画像</b><span>${state.profile.foundation||'已有基础'} · ${state.profile.style||'学习偏好'} · ${state.profile.confidence||'信心信息'}</span><button class="btn small" onclick="go('profile')">查看或修改</button></div>`:'';
 return `<section class="onboard"><div class="chat-pane"><div class="chat-head"><div class="brand"><span class="logo">P</span>Pathly</div><span class="pill green"><span class="dot"></span> ${repeat?'新建学习路径':'首次 Onboarding'}</span></div>${reuse}<div class="chat-log">${history}<div class="quick">${q.quick.map(x=>`<button onclick="answer('${x}')">${x} →</button>`).join('')}</div></div>${q.key==='confirm'?'':`<div class="composer"><input id="customInput" placeholder="${q.placeholder}" onkeydown="if(event.key==='Enter')answer(this.value)"><button class="btn primary" onclick="answer($('#customInput').value)">发送 ↑</button></div>`}</div><aside class="profile-pane"><div class="profile-card"><span class="eyebrow">${repeat?'New learning goal':'Learner profile'}</span><h2 style="margin-top:8px">${repeat?'规划一个新目标':(state.profile.name||'正在认识你')}</h2><p class="muted">${repeat?'已收集的个人信息会自动沿用，本次只确认新的目标与时间。':'这里只展示你提供的信息，可以在确认前修改。'}</p><div class="profile-meter"><span style="width:${progress()}%"></span></div>${[['姓名','name'],['学习目标','goal'],['目标天数','days'],['每日投入（分钟）','minutes'],['已有基础','foundation'],['学习偏好','style'],['当前信心','confidence']].map(([label,key])=>`<div class="profile-item ${repeat&&!['goal','days','minutes'].includes(key)?'reused':''}"><label>${label}${repeat&&!['goal','days','minutes'].includes(key)?' · 已沿用':''}</label><input value="${state.profile[key]??''}" placeholder="待填写" ${repeat&&!['goal','days','minutes'].includes(key)?'disabled':''} onchange="editProfile('${key}',this.value)"></div>`).join('')}${q.key==='confirm'?`<button class="btn primary" style="width:100%;margin-top:18px" onclick="submitOnboarding()">确认并生成新的学习路径 →</button>`:''}${repeat?`<button class="btn ghost" style="width:100%;margin-top:8px" onclick="go('dashboard')">取消，返回当前路径</button>`:''}<p class="muted" style="font-size:12px;margin-top:15px">新路径不会覆盖已有学习路径。</p></div></aside></section>`;
}
function editProfile(key,value){state.profile[key]=['days','minutes'].includes(key)?parseInt(value)||null:value;persist()}
function answer(value){if(!value?.trim())return;const qs=activeQuestions(),q=qs[state.step];let stored=value.trim();if(q.key==='days'||q.key==='minutes')stored=parseInt(stored);state.profile[q.key]=stored;state.messages.push({role:'user',text:value.trim()});state.step++;state.messages.push({role:'agent',text:qs[state.step].text});saveRender()}
function profilePayload(){const f=state.profile.foundation.toLowerCase();const confidence=state.profile.confidence;return {user_id:state.userId||undefined,name:state.profile.name,goal_text:state.profile.goal,target_days:Number(state.profile.days),daily_minutes:Number(state.profile.minutes),academic_level:'unspecified',domain:'user-defined',programming_foundation:f.includes('编程')||f.includes('python')?4:2,math_foundation:f.includes('数学')?4:2,prior_knowledge_level:f.includes('从零')?1:3,known_topics:f.includes('python')?['Python']:[],preferred_style:state.profile.style,confidence_level:confidence.includes('较高')?4:confidence.includes('较低')?2:3}}
async function submitOnboarding(){if(!state.profile.name||!state.profile.goal||!state.profile.days||!state.profile.minutes){toast('请先完整填写姓名、目标和时间');return}state.screen='planning';state.planError=null;state.planClarification=null;state.confirmedMappings={};state.planTick=0;saveRender();runPlanning()}
async function runPlanning(){let finished=false;const ticker=setInterval(()=>{if(!finished){state.planTick=Math.min(5,state.planTick+1);persist();render()}},700);try{const method=state.userId?'PATCH':'POST',url=state.userId?`/api/profiles/${state.userId}`:'/api/profiles';const saved=await api(url,{method,body:JSON.stringify(profilePayload())});state.userId=saved.data.user_id;const result=await api('/api/plans',{method:'POST',body:JSON.stringify({user_id:state.userId,goal_text:state.profile.goal,confirmed_mappings:state.confirmedMappings||{}})});state.planRecord=result.data;state.plan=result.data.plan;state.planNodes=nodesFromPlan(state.plan);state.planTick=6;state.screen='dashboard';state.onboardingMode='repeat';await refreshPlans()}catch(error){state.planError=error.message;state.planClarification=error.code==='planning_clarification_required'?error.details?.mappings||null:null;state.planTick=0}finally{finished=true;clearInterval(ticker);saveRender()}}
function nodesFromPlan(plan){const list=[];(plan?.days||[]).forEach(day=>(day.focus_topics||[]).forEach(topic=>{const i=list.length,col=i%4,row=Math.floor(i/4);list.push({id:i+1,day:day.day,title:topic,x:5+col*24,y:14+row*37+(col%2?8:0),status:day.day===1?'current':'future',min:Math.max(1,Math.round((day.estimated_minutes||0)/(day.focus_topics.length||1))),reason:day.reason||'根据先修关系和时间约束安排',prerequisites:day.prerequisite_bridge||[]})}));return list}
function clarificationPanel(){const mappings=state.planClarification||[],confirmations=[],unmatched=[];mappings.forEach(m=>{(m.unmatched_terms||[]).forEach(x=>unmatched.push(x));(m.confirmation_required||[]).forEach(item=>(item.candidates||[]).forEach(candidate=>confirmations.push({query:item.query||item.requested_term,name:candidate.name,score:candidate.score}))) });const unique=[...new Map(confirmations.map(x=>[`${x.query}|${x.name}`,x])).values()];if(!unique.length&&!unmatched.length)return '';return `<div class="clarification"><b>请确认你想学习的知识主题</b>${unmatched.length?`<p class="muted">暂未找到：${[...new Set(unmatched)].join('、')}</p>`:''}${unique.map(x=>`<button class="candidate" onclick="confirmMapping('${encodeURIComponent(x.query)}','${encodeURIComponent(x.name)}')"><span>${x.name}</span><small>匹配度 ${Math.round(x.score*100)}% · 选择并重新规划</small></button>`).join('')}</div>`}
function confirmMapping(query,name){state.confirmedMappings={...(state.confirmedMappings||{}),[decodeURIComponent(query)]:decodeURIComponent(name)};state.planError=null;state.planClarification=null;saveRender();runPlanning()}
function planning(){const steps=['解析学习目标','映射知识图谱节点','检查先修知识','规划主题顺序','分配每日学习时间','保存学习路径'];return `<section class="planning"><div class="brand"><span class="logo">P</span>Pathly</div><div class="planner-layout"><div><span class="eyebrow">Planning agent</span><h1>${state.planError?'暂时无法生成路径':'正在规划你的学习路径'}</h1><p>${state.planError?'你的画像已经保存，但知识规划服务没有成功完成。系统没有为你生成虚假计划。':'Pathly 正在使用你的画像和真实知识图谱。'}</p>${state.planError?`<div class="card" style="color:#17221e"><b>发生了什么</b><p>${state.planError}</p>${clarificationPanel()}<button class="btn primary" onclick="state.planError=null;saveRender();runPlanning()">重新尝试</button> <button class="btn" onclick="state.screen='onboarding';saveRender()">返回修改目标</button>${state.planRecord?` <button class="btn" onclick="returnToCurrentPath()">返回当前学习路径</button>`:''}</div>`:`<div class="steps">${steps.map((s,i)=>`<div class="step ${i<state.planTick?'done':i===state.planTick?'current':''}"><b>${i<state.planTick?'✓':i+1}</b>${s}</div>`).join('')}</div>`}</div><div class="plan-canvas"><div class="orbit"></div><div class="pnode" style="left:38%;top:42%">${state.planError?'规划未完成':'正在查询知识关系…'}</div></div></div></section>`}
function shell(content,active='dashboard'){return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="logo">P</span><div>Pathly<small>PERSONAL LEARNING</small></div></div><nav class="nav"><button class="${active==='dashboard'?'active':''}" onclick="go('dashboard')"><span class="ico">⌘</span>学习路径</button><button onclick="toast('每日学习将在下一阶段接入真实内容')"><span class="ico">◫</span>今日学习</button><button onclick="toast('学习记录将在完成真实学习后出现')"><span class="ico">◷</span>学习记录</button><button class="${active==='profile'?'active':''}" onclick="go('profile')"><span class="ico">♙</span>个人画像</button></nav><div class="side-foot"><b>${state.profile.goal}</b><br>${state.planRecord?.mode==='fallback'?'JSON KG 回退':'Neo4j 实时规划'}</div></aside><main class="main"><header class="topbar"><span class="eyebrow">Personal learning space</span><div class="top-actions"><button class="btn small" onclick="startNewPath()">＋ 新建学习路径</button><span class="avatar">${state.profile.name.slice(0,1)}</span></div></header>${content}</main></div>`}
function dashboard(){const p=state.plan,feas=p.feasibility||{},sources=state.planRecord?.sources||[];return `<div class="dashboard-head"><div><span class="eyebrow">Your learning paths</span><h1>${state.profile.name}，选择并继续你的学习路径</h1><p class="muted">你可以为变化中的目标创建不同路径，彼此不会覆盖。</p></div></div>${pathSwitcher()}<section class="hero"><div><span class="pill ${state.planRecord?.mode==='live'?'green':'lime'}">${state.planRecord?.mode==='live'?'Neo4j 实时规划':'JSON KG 回退规划'}</span><h1>${p.target_topics?.join('、')||state.profile.goal}</h1><p class="muted">${feas.warning||`计划共 ${feas.requested_days} 天，每天约 ${feas.daily_minutes} 分钟。`}</p><small>数据来源：${sources.join(' + ')}</small></div></section><div class="stats"><div class="stat"><span class="muted">目标天数</span><strong>${feas.requested_days}</strong></div><div class="stat"><span class="muted">每日投入</span><strong>${feas.daily_minutes}m</strong></div><div class="stat"><span class="muted">路径节点</span><strong>${state.planNodes.length}</strong></div><div class="stat"><span class="muted">计划版本</span><strong>v${state.planRecord.version}</strong></div></div><section class="card map-card"><div class="map-head"><div><h2>学习路径</h2><span class="muted">所有节点均来自 Planning Agent 返回结果</span></div><div class="seg"><button class="${state.view==='map'?'active':''}" onclick="setView('map')">知识关系</button><button class="${state.view==='time'?'active':''}" onclick="setView('time')">时间线</button></div></div>${pathView()}</section>`}
function pathView(){const ns=state.planNodes;if(state.view==='time')return `<div class="timeline">${ns.map(n=>`<div class="day-card ${n.day===1?'current':''}"><small>DAY ${n.day}</small><h3>${n.title}</h3><span class="muted">${n.min} 分钟</span></div>`).join('')}</div>`;return `<div class="learning-map"><svg>${ns.slice(0,-1).map((n,i)=>`<line x1="${n.x+7}%" y1="${n.y+8}%" x2="${ns[i+1].x+7}%" y2="${ns[i+1].y+8}%"/>`).join('')}</svg>${ns.map(n=>`<button class="map-node ${n.status}" style="left:${n.x}%;top:${n.y}%" onclick="nodeInfo(${n.id})"><small>DAY ${n.day} · ${n.min} MIN</small>${n.title}</button>`).join('')}</div>`}
function nodeInfo(id){const n=state.planNodes.find(x=>x.id===id);if(!n)return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="modal-card"><span class="pill">Day ${n.day}</span><h2>${n.title}</h2><p>预计 ${n.min} 分钟</p><div class="concept"><b>规划理由</b><br>${n.reason}</div><p class="muted">先修桥接：${n.prerequisites.join('、')||'无'}</p><button class="btn primary" onclick="this.closest('.modal').remove()">关闭</button></div></div>`)}
function profilePage(){return `<div><span class="eyebrow">Learner profile</span><h1>你的长期学习者画像</h1><p class="muted">姓名、基础、偏好和信心会在新路径中自动沿用；学习目标与时间属于每一条独立路径。</p></div><div class="card profile-summary" style="max-width:760px;margin-top:24px">${[['姓名','name'],['已有基础','foundation'],['学习偏好','style'],['信心','confidence']].map(([l,k])=>`<div class="profile-item"><label>${l}</label><input value="${state.profile[k]}" onchange="editProfile('${k}',this.value)"></div>`).join('')}<button class="btn primary" style="margin-top:18px" onclick="saveBaseProfile()">保存画像修改</button></div><div style="margin-top:28px"><h2>你的学习路径（${state.plans.length}）</h2>${pathSwitcher()}</div>`}

function pathSwitcher(){if(!state.plans.length)return '';return `<div class="path-switcher">${state.plans.map(r=>`<div class="path-card"><button class="path-choice ${r.plan_id===state.planRecord?.plan_id?'active':''}" onclick="selectPlan('${r.plan_id}')"><small>${r.plan_id===state.planRecord?.plan_id?'当前路径':'学习路径'} · v${r.version}</small><b>${r.goal_text||r.plan?.target_topics?.join('、')||'未命名目标'}</b><span>${r.plan?.feasibility?.requested_days||'-'} 天 · ${r.plan?.feasibility?.daily_minutes||'-'} 分钟/天</span></button><button class="path-delete" onclick="requestDeletePath('${r.plan_id}')">删除</button></div>`).join('')}<button class="path-choice add" onclick="startNewPath()"><b>＋ 新建学习路径</b><span>沿用个人画像，只填写新目标和时间</span></button></div>${state.deletePathCandidate?`<div class="modal" onclick="if(event.target===this)cancelDeletePath()"><div class="modal-card"><span class="pill">删除学习路径</span><h2>确定删除这条路径吗？</h2><p>这会删除该路径下所有版本、路径上下文和 V4 缓存，且无法在页面中恢复。</p><div class="concept"><b>${state.deletePathCandidate.goal_text||state.deletePathCandidate.plan?.target_topics?.join('、')||'未命名目标'}</b><br>路径 ID：${state.deletePathCandidate.path_id}</div>${state.deletePathError?`<p class="muted" style="color:#a33">删除失败：${state.deletePathError}</p>`:''}<div style="display:flex;gap:10px;justify-content:flex-end;margin-top:16px"><button class="btn" onclick="cancelDeletePath()">取消</button><button class="btn danger" onclick="confirmDeletePath()">确认删除</button></div></div></div>`:''}`}
function startNewPath(){state.onboardingMode='repeat';state.screen='onboarding';state.step=0;state.messages=[];state.profile.goal='';state.profile.days=null;state.profile.minutes=null;state.planError=null;state.planClarification=null;state.confirmedMappings={};saveRender()}
function requestDeletePath(planId){const record=state.plans.find(x=>x.plan_id===planId);if(!record)return;state.deletePathCandidate=record;state.deletePathError=null;saveRender()}
function cancelDeletePath(){state.deletePathCandidate=null;state.deletePathError=null;saveRender()}
async function confirmDeletePath(){const record=state.deletePathCandidate;if(!record)return;try{await api(`/api/plans/${record.path_id}`,{method:'DELETE',body:JSON.stringify({user_id:state.userId})});state.deletePathCandidate=null;state.deletePathError=null;await refreshPlans();if(state.planRecord?.path_id===record.path_id){const next=state.plans[0]||null;if(next){selectPlan(next.plan_id)}else{state.planRecord=null;state.plan=null;state.planNodes=[];state.screen='onboarding';state.onboardingMode='first'}}saveRender();toast('已删除这条学习路径')}catch(error){state.deletePathError=error.message||'删除失败';saveRender()}}
function selectPlan(planId){const record=state.plans.find(x=>x.plan_id===planId);if(!record)return;state.planRecord=record;state.plan=record.plan;state.planNodes=nodesFromPlan(record.plan);const snap=record.profile_snapshot||{};state.profile.goal=record.goal_text||snap.goal_text||record.plan?.target_topics?.join('、')||'';state.profile.days=snap.target_days||record.plan?.feasibility?.requested_days||null;state.profile.minutes=snap.daily_minutes||record.plan?.feasibility?.daily_minutes||null;state.screen='dashboard';saveRender()}
async function refreshPlans(){if(!state.userId)return;const response=await api(`/api/users/${state.userId}/plans`),records=response.data||[],latest=new Map();records.forEach(r=>{const current=latest.get(r.path_id);if(!current||r.version>current.version)latest.set(r.path_id,r)});state.plans=[...latest.values()].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}
async function saveBaseProfile(){if(!state.userId)return;const saved=await api(`/api/profiles/${state.userId}`,{method:'PATCH',body:JSON.stringify(profilePayload())});toast('个人画像已更新');state.profile.name=saved.data.name;persist()}
async function hydrate(){if(!state.userId)return;try{await refreshPlans();if(state.planRecord){const current=state.plans.find(x=>x.plan_id===state.planRecord.plan_id);if(current){state.planRecord=current;state.plan=current.plan;state.planNodes=nodesFromPlan(current.plan)}}persist();render()}catch(error){console.warn('Unable to restore learning paths',error)}}

function returnToCurrentPath(){if(!state.planRecord||!state.plan)return;state.planError=null;state.planClarification=null;state.planNodes=nodesFromPlan(state.plan);state.screen='dashboard';saveRender()}
function setView(view){state.view=view;saveRender()}function go(screen){state.screen=screen;saveRender();scrollTo(0,0)}
function render(){const app=$('#app');if(state.screen==='planning')app.innerHTML=planning();else if(state.screen==='dashboard'&&state.plan&&state.planNodes.length)app.innerHTML=shell(dashboard());else if(state.screen==='profile')app.innerHTML=shell(profilePage(),'profile');else app.innerHTML=onboarding()}
render();hydrate();
